# Generated by Django 5.0.3 on 2024-03-28 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('photo', models.FileField(upload_to='images/')),
                ('rating', models.IntegerField()),
                ('year', models.IntegerField()),
                ('video', models.FileField(upload_to='movies/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='category')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.director', verbose_name='director')),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movie',
            },
        ),
    ]
