# Generated by Django 5.0.3 on 2024-03-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
